if(EXISTS "C:/GitProjects/Distributed-Chat-Server/build-clean/user_test-b12d07c_tests.cmake")
  include("C:/GitProjects/Distributed-Chat-Server/build-clean/user_test-b12d07c_tests.cmake")
else()
  add_test(user_test_NOT_BUILT-b12d07c user_test_NOT_BUILT-b12d07c)
endif()
